const articles = [
    {
        id: 1,
        title: 'Belajar Menjadi Konten Kreator',
        overview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum?',
        duration: 15,
        imageUrl: '/images/item-list-content-img.jpg',
    },
    {
        id: 2,
        title: 'Jenis-jenis Konten dan Platform-nya',
        overview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae?Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum?',
        duration: 15,
        imageUrl: '/images/item-list-content-img.jpg',
    },
    {
        id: 3,
        title: 'Cara Agar Dapat Menarik Viewer',
        overview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae?Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum?',
        duration: 15,
        imageUrl: '/images/item-list-content-img.jpg',
    },
    {
        id: 4,
        title: 'Macam-macam Cara Mengahasilkan Income',
        overview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae?Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum?',
        duration: 15,
        imageUrl: '/images/item-list-content-img.jpg',
    },
    {
        id: 5,
        title: 'Tricks and Tips Agar Trending',
        overview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae?Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum?',
        duration: 15,
        imageUrl: '/images/item-list-content-img.jpg',
    },
    {
        id: 6,
        title: 'Tutorial Videografi',
        overview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae?Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum?',
        duration: 15,
        imageUrl: '/images/item-list-content-img.jpg',
    },
    {
        id: 7,
        title: 'Tarik Viewer mu Dengan Thumbnail Yang Menarik',
        overview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae?Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat similique sequi, itaque recusandae nulla quo qui eveniet reiciendis necessitatibus ipsa. Quod magni facilis quo, laborum modi iste reprehenderit numquam repudiandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet dolores error, porro dolorem mollitia fuga beatae similique aliquam aut. Accusamus quas nesciunt laborum incidunt esse quidem, dolore dolores harum?',
        duration: 15,
        imageUrl: '/images/item-list-content-img.jpg',
    },
];
   
function getDataList() {
    return articles;
}

function getData(id) {
    if (!id) {
        return null;
    }

    const filteredArticles = articles.filter((article) => article.id === id);

    if (!filteredArticles.length) {
        return null
    }

    return filteredArticles[0];
}

export { getDataList, getData };